export enum TypeTask {
  SET_ALERT = 'SET_ALERT',
  REMOVE_ALERT = 'REMOVE_ALERT',
  DROPDOWN_FORM = 'DROPDOWN_FORM',
  SETCONTROL_FORM = 'SETCONTROL_FORM',
  SETPRIORITY_TASK = 'SETPRIORITY_TASK',
  CLEAR_FORM = 'CLEAR_FORM',
  GET_TASKS = 'GET_TASKS',
  ADD_TASK = 'ADD_TASK',
  DELETE_TASK = 'DELETE_TASK',
  SET_LOADING = 'SET_LOADING',
  ERROR_TASK = 'ERROR_TASK'
}
